[project]
site_name = "Jershlabs Wiki"

nav = [
    {"Home" = "index.md"},
    {"Guides" = [
        "mounting-drives.md",
        "setting-up-git.md",
        "setting-up-semaphore.md",
        "setting-up-terraform.md",
        "setting-up-wsl.md",
    ]}
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
